### ISSUE TITLE
impossible to halt program execution

### ISSUE THREAD

**Issue by HiddenToad** [inh2102/spam-truth-social#6]
i think we should figure out how to implement KeyboardInterrupt (CTRL+C). it's kind of lame to not be able to halt execution. i've tried some stuff, but nothing has actually worked yet (try/except not doing anything). any ideas?

**Comment by inh2102** [comment]
@HiddenToad good work on the other stuff! i'll toy around with error handling. also going to work on making the outputs update # of reg's on same line rather than spitting a new one each time

**Comment by inh2102** [comment]
@HiddenToad maybe I misunderstand - ctrl + C KeyboardInterrupt works for me in the command line. there's probably a more elegant way to have the program terminate, but is it not the same for you? 

but yes, error messages do pop up for me and it seems like this is when threads have error `requests.exceptions.ConnectionError: ('Connection aborted.', OSError(22, 'Invalid argument')` and so we use 

try:
 (threading fn.)

except requests.exceptions.ConnectionError:
  (pass/continue)

?

**Comment by HiddenToad** [comment]
issue solved!
