### ISSUE TITLE
more but slower proxies?

### ISSUE THREAD

**Issue by HiddenToad** [inh2102/spam-truth-social#8]
this is only a proposition. the site i got the proxies from has more proxies than we're using, but i've limited it to ones with a max timeout of 3000ms. i could add a lot more, but we would be getting up to 5000 or 8000 ms timeouts, and that could seriously hurt the runtime of the script. what do you think?

**Comment by inh2102** [comment]
up to you but i lean against, if they really look at IP i doubt 500 vs 1,000 unique IPs is a meaningful distinction

**Comment by HiddenToad** [comment]
that seems to make sense to me!! leaving proxy list the same until i can expand with more low-timeout proxies.
